"""Forge POC - Package & WDAC Policy Generator"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional
import xml.etree.ElementTree as ET

from forge.config import settings
from forge.models import InstallerMetadata, AIAnalysisResult, WDACPolicy

logger = logging.getLogger(__name__)


WDAC_POLICY_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<SiPolicy xmlns="urn:schemas-microsoft-com:sipolicy" PolicyType="Base Policy">
  <VersionEx>10.0.0.0</VersionEx>
  <PolicyID>{{{policy_id}}}</PolicyID>
  <BasePolicyID>{{{policy_id}}}</BasePolicyID>
  <PlatformID>{{2E07F7E4-194C-4D20-B7C9-6F44A6C5A234}}</PlatformID>
  <Rules>
    <Rule>
      <Option>Enabled:Unsigned System Integrity Policy</Option>
    </Rule>
    <Rule>
      <Option>Enabled:Audit Mode</Option>
    </Rule>
  </Rules>
  <EKUs />
  <FileRules>
{file_rules}
  </FileRules>
  <Signers />
  <SigningScenarios>
    <SigningScenario Value="131" ID="ID_SIGNINGSCENARIO_WINDOWS" FriendlyName="Kernel Mode">
      <ProductSigners />
    </SigningScenario>
    <SigningScenario Value="12" ID="ID_SIGNINGSCENARIO_USERMODE" FriendlyName="User Mode">
      <ProductSigners>
        <FileRulesRef>
{file_rules_ref}
        </FileRulesRef>
      </ProductSigners>
    </SigningScenario>
  </SigningScenarios>
  <UpdatePolicySigners />
  <CiSigners />
  <HvciOptions>0</HvciOptions>
</SiPolicy>"""


class Packager:
    """Package and WDAC policy generation service."""
    
    async def create_package(
        self, 
        metadata: InstallerMetadata, 
        analysis: AIAnalysisResult
    ) -> dict:
        """Create a deployment package with install scripts."""
        
        package_name = self._sanitize_name(metadata.product_name or metadata.filename)
        package_dir = settings.packages_dir / package_name
        package_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate install script
        install_script = self._generate_install_script(metadata, analysis)
        install_path = package_dir / "Install.ps1"
        install_path.write_text(install_script)
        
        # Generate uninstall script
        uninstall_script = self._generate_uninstall_script(metadata, analysis)
        uninstall_path = package_dir / "Uninstall.ps1"
        uninstall_path.write_text(uninstall_script)
        
        # Generate detection script
        detection_script = self._generate_detection_script(metadata)
        detection_path = package_dir / "Detection.ps1"
        detection_path.write_text(detection_script)
        
        # Generate metadata file
        metadata_content = self._generate_metadata_file(metadata, analysis)
        metadata_path = package_dir / "package.json"
        metadata_path.write_text(metadata_content)
        
        logger.info(f"Package created at: {package_dir}")
        
        return {
            "package_dir": str(package_dir),
            "install_script": str(install_path),
            "uninstall_script": str(uninstall_path),
            "detection_script": str(detection_path),
        }
    
    async def generate_wdac_policy(
        self, 
        metadata: InstallerMetadata, 
        analysis: AIAnalysisResult
    ) -> WDACPolicy:
        """Generate a WDAC policy for the application."""
        
        import uuid
        policy_id = str(uuid.uuid4()).upper()
        policy_name = f"Forge_{self._sanitize_name(metadata.product_name or metadata.filename)}"
        
        # Generate file rules based on the installer
        file_rules, file_rules_ref, rules_list = self._generate_file_rules(metadata)
        
        policy_xml = WDAC_POLICY_TEMPLATE.format(
            policy_id=policy_id,
            file_rules=file_rules,
            file_rules_ref=file_rules_ref,
        )
        
        # Save policy
        policy_path = settings.policies_dir / f"{policy_name}.xml"
        policy_path.write_text(policy_xml)
        
        logger.info(f"WDAC policy created: {policy_path}")
        
        return WDACPolicy(
            policy_name=policy_name,
            policy_xml=policy_xml,
            rules=rules_list,
            generated_at=datetime.utcnow(),
        )
    
    def _sanitize_name(self, name: str) -> str:
        """Sanitize a name for use in filenames."""
        import re
        # Remove invalid characters
        name = re.sub(r'[<>:"/\\|?*]', '', name)
        # Replace spaces with underscores
        name = name.replace(' ', '_')
        # Limit length
        return name[:50]
    
    def _generate_install_script(
        self, 
        metadata: InstallerMetadata, 
        analysis: AIAnalysisResult
    ) -> str:
        """Generate PowerShell install script."""
        
        return f'''<#
.SYNOPSIS
    Install script for {metadata.product_name or metadata.filename}
    Generated by Forge POC

.DESCRIPTION
    Silent installation with logging
    Confidence: {analysis.confidence:.0%}
    
.NOTES
    {analysis.reasoning}
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\\Forge_Install_{self._sanitize_name(metadata.filename)}.log"

function Write-Log {{
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}}

try {{
    Write-Log "Starting installation of {metadata.product_name or metadata.filename}"
    Write-Log "Installer: {metadata.filename}"
    Write-Log "Version: {metadata.product_version or 'Unknown'}"
    
    $installerPath = Join-Path $PSScriptRoot "{metadata.filename}"
    
    if (-not (Test-Path $installerPath)) {{
        throw "Installer not found: $installerPath"
    }}
    
    Write-Log "Executing: {analysis.install_command}"
    
    # Execute installation
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "{analysis.install_command}" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {{
        Write-Log "Installation completed successfully (Exit code: $($process.ExitCode))"
        if ($process.ExitCode -eq 3010) {{
            Write-Log "Note: Reboot required"
        }}
        exit 0
    }} else {{
        throw "Installation failed with exit code: $($process.ExitCode)"
    }}
}}
catch {{
    Write-Log "ERROR: $_"
    exit 1
}}
'''
    
    def _generate_uninstall_script(
        self, 
        metadata: InstallerMetadata, 
        analysis: AIAnalysisResult
    ) -> str:
        """Generate PowerShell uninstall script."""
        
        return f'''<#
.SYNOPSIS
    Uninstall script for {metadata.product_name or metadata.filename}
    Generated by Forge POC
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\\Forge_Uninstall_{self._sanitize_name(metadata.filename)}.log"

function Write-Log {{
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}}

try {{
    Write-Log "Starting uninstallation of {metadata.product_name or metadata.filename}"
    
    # Try uninstall command
    Write-Log "Executing: {analysis.uninstall_command}"
    
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "{analysis.uninstall_command}" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {{
        Write-Log "Uninstallation completed successfully"
        exit 0
    }} else {{
        throw "Uninstallation failed with exit code: $($process.ExitCode)"
    }}
}}
catch {{
    Write-Log "ERROR: $_"
    exit 1
}}
'''
    
    def _generate_detection_script(self, metadata: InstallerMetadata) -> str:
        """Generate PowerShell detection script for Intune/SCCM."""
        
        product_name = metadata.product_name or metadata.filename
        
        return f'''<#
.SYNOPSIS
    Detection script for {product_name}
    Generated by Forge POC
    
.DESCRIPTION
    Returns exit code 0 if application is installed, 1 if not
#>

$ProductName = "{product_name}"
$ExpectedVersion = "{metadata.product_version or '*'}"

# Check registry (64-bit)
$uninstallPath = "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
$installed = Get-ChildItem $uninstallPath -ErrorAction SilentlyContinue | 
    Get-ItemProperty | 
    Where-Object {{ $_.DisplayName -like "*$ProductName*" }}

# Check registry (32-bit on 64-bit OS)
$uninstallPath32 = "HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
if (-not $installed) {{
    $installed = Get-ChildItem $uninstallPath32 -ErrorAction SilentlyContinue | 
        Get-ItemProperty | 
        Where-Object {{ $_.DisplayName -like "*$ProductName*" }}
}}

if ($installed) {{
    Write-Host "Detected: $($installed.DisplayName) v$($installed.DisplayVersion)"
    exit 0
}} else {{
    Write-Host "Not detected: $ProductName"
    exit 1
}}
'''
    
    def _generate_metadata_file(
        self, 
        metadata: InstallerMetadata, 
        analysis: AIAnalysisResult
    ) -> str:
        """Generate package metadata JSON."""
        import json
        
        return json.dumps({
            "name": metadata.product_name or metadata.filename,
            "version": metadata.product_version or "unknown",
            "manufacturer": metadata.manufacturer or "unknown",
            "installer": {
                "filename": metadata.filename,
                "type": metadata.installer_type.value,
                "hash": metadata.file_hash,
                "size": metadata.file_size,
            },
            "installation": {
                "command": analysis.install_command,
                "switches": analysis.silent_switches,
                "uninstall_command": analysis.uninstall_command,
            },
            "analysis": {
                "confidence": analysis.confidence,
                "reasoning": analysis.reasoning,
                "known_issues": analysis.known_issues,
            },
            "generated_by": "Forge POC",
            "generated_at": datetime.utcnow().isoformat(),
        }, indent=2)
    
    def _generate_file_rules(self, metadata: InstallerMetadata) -> tuple[str, str, list]:
        """Generate WDAC file rules."""
        
        rule_id = f"ID_ALLOW_{self._sanitize_name(metadata.filename).upper()}"
        
        # Create hash-based rule
        file_rule = f'''    <Allow ID="{rule_id}" 
           FriendlyName="{metadata.product_name or metadata.filename}" 
           Hash="{metadata.file_hash}" />'''
        
        file_rule_ref = f'          <FileRuleRef RuleID="{rule_id}" />'
        
        rules_list = [{
            "type": "hash",
            "id": rule_id,
            "name": metadata.product_name or metadata.filename,
            "hash": metadata.file_hash,
        }]
        
        return file_rule, file_rule_ref, rules_list
