<#
.SYNOPSIS
    Detection script for 54c84aa7_SampleApp
    Generated by Forge POC
    
.DESCRIPTION
    Returns exit code 0 if application is installed, 1 if not
#>

$ProductName = "54c84aa7_SampleApp"
$ExpectedVersion = "1.0.0"

# Check registry (64-bit)
$uninstallPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"
$installed = Get-ChildItem $uninstallPath -ErrorAction SilentlyContinue | 
    Get-ItemProperty | 
    Where-Object { $_.DisplayName -like "*$ProductName*" }

# Check registry (32-bit on 64-bit OS)
$uninstallPath32 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
if (-not $installed) {
    $installed = Get-ChildItem $uninstallPath32 -ErrorAction SilentlyContinue | 
        Get-ItemProperty | 
        Where-Object { $_.DisplayName -like "*$ProductName*" }
}

if ($installed) {
    Write-Host "Detected: $($installed.DisplayName) v$($installed.DisplayVersion)"
    exit 0
} else {
    Write-Host "Not detected: $ProductName"
    exit 1
}
