<#
.SYNOPSIS
    Uninstall script for 54c84aa7_SampleApp
    Generated by Forge POC
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\Forge_Uninstall_54c84aa7_SampleApp_1.0.0_x64.msi.log"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}

try {
    Write-Log "Starting uninstallation of 54c84aa7_SampleApp"
    
    # Try uninstall command
    Write-Log "Executing: msiexec /x "54c84aa7_SampleApp_1.0.0_x64.msi" /qn"
    
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "msiexec /x "54c84aa7_SampleApp_1.0.0_x64.msi" /qn" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {
        Write-Log "Uninstallation completed successfully"
        exit 0
    } else {
        throw "Uninstallation failed with exit code: $($process.ExitCode)"
    }
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
