<#
.SYNOPSIS
    Uninstall script for 322cdaff_NotepadPlus
    Generated by Forge POC
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\Forge_Uninstall_322cdaff_NotepadPlus_8.5_Setup.exe.log"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}

try {
    Write-Log "Starting uninstallation of 322cdaff_NotepadPlus"
    
    # Try uninstall command
    Write-Log "Executing: Unknown"
    
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "Unknown" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {
        Write-Log "Uninstallation completed successfully"
        exit 0
    } else {
        throw "Uninstallation failed with exit code: $($process.ExitCode)"
    }
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
