<#
.SYNOPSIS
    Install script for ea3ea9c4_NotepadPlus
    Generated by Forge POC

.DESCRIPTION
    Silent installation with logging
    Confidence: 40%
    
.NOTES
    Basic analysis based on installer type. AI analysis unavailable.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\Forge_Install_ea3ea9c4_NotepadPlus_8.5_Setup.exe.log"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}

try {
    Write-Log "Starting installation of ea3ea9c4_NotepadPlus"
    Write-Log "Installer: ea3ea9c4_NotepadPlus_8.5_Setup.exe"
    Write-Log "Version: 8.5"
    
    $installerPath = Join-Path $PSScriptRoot "ea3ea9c4_NotepadPlus_8.5_Setup.exe"
    
    if (-not (Test-Path $installerPath)) {
        throw "Installer not found: $installerPath"
    }
    
    Write-Log "Executing: "ea3ea9c4_NotepadPlus_8.5_Setup.exe" /S /s"
    
    # Execute installation
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", ""ea3ea9c4_NotepadPlus_8.5_Setup.exe" /S /s" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {
        Write-Log "Installation completed successfully (Exit code: $($process.ExitCode))"
        if ($process.ExitCode -eq 3010) {
            Write-Log "Note: Reboot required"
        }
        exit 0
    } else {
        throw "Installation failed with exit code: $($process.ExitCode)"
    }
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
