<#
.SYNOPSIS
    Install script for 8f516359_54c84aa7_SampleApp
    Generated by Forge POC

.DESCRIPTION
    Silent installation with logging
    Confidence: 40%
    
.NOTES
    Basic analysis based on installer type. AI analysis unavailable.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$LogPath = "$env:TEMP\Forge_Install_8f516359_54c84aa7_SampleApp_1.0.0_x64.msi.log"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Tee-Object -FilePath $LogPath -Append
}

try {
    Write-Log "Starting installation of 8f516359_54c84aa7_SampleApp"
    Write-Log "Installer: 8f516359_54c84aa7_SampleApp_1.0.0_x64.msi"
    Write-Log "Version: 1.0.0"
    
    $installerPath = Join-Path $PSScriptRoot "8f516359_54c84aa7_SampleApp_1.0.0_x64.msi"
    
    if (-not (Test-Path $installerPath)) {
        throw "Installer not found: $installerPath"
    }
    
    Write-Log "Executing: msiexec /i "8f516359_54c84aa7_SampleApp_1.0.0_x64.msi" /qn /quiet /passive /norestart ALLUSERS=1"
    
    # Execute installation
    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "msiexec /i "8f516359_54c84aa7_SampleApp_1.0.0_x64.msi" /qn /quiet /passive /norestart ALLUSERS=1" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 3010) {
        Write-Log "Installation completed successfully (Exit code: $($process.ExitCode))"
        if ($process.ExitCode -eq 3010) {
            Write-Log "Note: Reboot required"
        }
        exit 0
    } else {
        throw "Installation failed with exit code: $($process.ExitCode)"
    }
}
catch {
    Write-Log "ERROR: $_"
    exit 1
}
